VIBE_ANCHORS = [
    {
        "description": "aggressive angry heavy metal hardcore rage intense",
        "genres": ["metal", "heavy-metal", "black-metal", "death-metal", "hardcore", "grindcore", "metalcore", "hard-rock", "industrial"],
        "year_range": None,
        "features": {
            "danceability": 0.35,
            "energy": 0.95,
            "loudness": -4.0,
            "speechiness": 0.1,
            "acousticness": 0.02,
            "instrumentalness": 0.1,
            "liveness": 0.2,
            "valence": 0.2,
            "tempo": 170.0,
            "key": 4,
            "mode": 0.1,
            "time_signature": 4,
        }
    },
    {
        "description": "calm peaceful relaxing sleep ambient quiet soft",
        "genres": ["ambient", "sleep", "new-age", "chill", "classical", "acoustic", "piano"],
        "year_range": None,
        "features": {
            "danceability": 0.25,
            "energy": 0.08,
            "loudness": -20.0,
            "speechiness": 0.03,
            "acousticness": 0.85,
            "instrumentalness": 0.7,
            "liveness": 0.08,
            "valence": 0.35,
            "tempo": 70.0,
            "key": 9,
            "mode": 0.3,
            "time_signature": 4,
        }
    },
    {
        "description": "pop hits happy upbeat fun party celebration euphoric joyful chart mainstream",
        "genres": ["pop", "party", "dance", "disco", "funk", "groove", "club"],
        "year_range": (2010, 2023),
        "features": {
            "danceability": 0.85,
            "energy": 0.8,
            "loudness": -5.0,
            "speechiness": 0.07,
            "acousticness": 0.1,
            "instrumentalness": 0.05,
            "liveness": 0.15,
            "valence": 0.9,
            "tempo": 125.0,
            "key": 0,
            "mode": 0.9,
            "time_signature": 4,
        }
    },
    {
        "description": "sad melancholic emotional lovesick lonely depressing",
        "genres": ["sad", "emo", "singer-songwriter", "indie-pop", "soul", "blues", "acoustic"],
        "year_range": None,
        "features": {
            "danceability": 0.35,
            "energy": 0.25,
            "loudness": -12.0,
            "speechiness": 0.05,
            "acousticness": 0.55,
            "instrumentalness": 0.1,
            "liveness": 0.1,
            "valence": 0.1,
            "tempo": 80.0,
            "key": 2,
            "mode": 0.1,
            "time_signature": 4,
        }
    },
    {
        "description": "workout training fitness running exercise pump power energy",
        "genres": ["edm", "hardstyle", "electronic", "hip-hop", "rock", "hard-rock", "drum-and-bass", "dance"],
        "year_range": (2010, 2023),
        "features": {
            "danceability": 0.75,
            "energy": 0.92,
            "loudness": -4.5,
            "speechiness": 0.12,
            "acousticness": 0.03,
            "instrumentalness": 0.15,
            "liveness": 0.15,
            "valence": 0.6,
            "tempo": 155.0,
            "key": 5,
            "mode": 0.7,
            "time_signature": 4,
        }
    },
    {
        "description": "late midnight drive dark moody atmospheric cinematic",
        "genres": ["trip-hop", "electronic", "ambient", "chill", "indie-pop", "goth", "psych-rock"],
        "year_range": (2000, 2023),
        "features": {
            "danceability": 0.45,
            "energy": 0.4,
            "loudness": -10.0,
            "speechiness": 0.05,
            "acousticness": 0.25,
            "instrumentalness": 0.3,
            "liveness": 0.1,
            "valence": 0.25,
            "tempo": 95.0,
            "key": 9,
            "mode": 0.2,
            "time_signature": 4,
        }
    },
    {
        "description": "club midnight groove rhythm track electronic rave techno house bpm dancing",
        "genres": ["techno", "house", "edm", "electro", "chicago-house", "deep-house", "detroit-techno",
                   "progressive-house", "minimal-techno", "trance", "dubstep", "drum-and-bass", "club",
                   "dance", "pop", "hip-hop"],
        "year_range": (2010, 2023),
        "features": {
            "danceability": 0.9,
            "energy": 0.88,
            "loudness": -5.5,
            "speechiness": 0.06,
            "acousticness": 0.02,
            "instrumentalness": 0.15,
            "liveness": 0.12,
            "valence": 0.65,
            "tempo": 130.0,
            "key": 8,
            "mode": 0.7,
            "time_signature": 4,
        }
    },
    {
        "description": "romantic love intimate sensual slow swaying",
        "genres": ["romance", "soul", "jazz", "pop", "r&b", "salsa", "tango", "samba"],
        "year_range": None,
        "features": {
            "danceability": 0.6,
            "energy": 0.35,
            "loudness": -10.0,
            "speechiness": 0.05,
            "acousticness": 0.4,
            "instrumentalness": 0.1,
            "liveness": 0.1,
            "valence": 0.55,
            "tempo": 90.0,
            "key": 7,
            "mode": 0.4,
            "time_signature": 3,
        }
    },
    {
        "description": "morning espresso sunday breakfast chill positive fresh start",
        "genres": ["acoustic", "folk", "singer-songwriter", "indie-pop", "soul", "jazz", "pop"],
        "year_range": None,
        "features": {
            "danceability": 0.5,
            "energy": 0.35,
            "loudness": -11.0,
            "speechiness": 0.04,
            "acousticness": 0.65,
            "instrumentalness": 0.1,
            "liveness": 0.1,
            "valence": 0.7,
            "tempo": 100.0,
            "key": 0,
            "mode": 0.8,
            "time_signature": 4,
        }
    },
    {
        "description": "hip hop rap",
        "genres": ["hip-hop", "rap", "trap", "dancehall", "groove", "funk"],
        "year_range": (2000, 2023),
        "features": {
            "danceability": 0.82,
            "energy": 0.72,
            "loudness": -6.0,
            "speechiness": 0.28,
            "acousticness": 0.08,
            "instrumentalness": 0.02,
            "liveness": 0.15,
            "valence": 0.55,
            "tempo": 110.0,
            "key": 9,
            "mode": 0.5,
            "time_signature": 4,
        }
    },
    {
        "description": "focus study concentration intense absorbed productivity calm instrumental",
        "genres": ["classical", "piano", "ambient", "new-age", "jazz", "instrumental", "minimal-techno"],
        "year_range": None,
        "features": {
            "danceability": 0.3,
            "energy": 0.25,
            "loudness": -14.0,
            "speechiness": 0.03,
            "acousticness": 0.5,
            "instrumentalness": 0.8,
            "liveness": 0.08,
            "valence": 0.4,
            "tempo": 88.0,
            "key": 0,
            "mode": 0.4,
            "time_signature": 4,
        }
    },
    {
        "description": "country folk western americana road trip guitar banjo",
        "genres": ["country", "folk", "acoustic", "guitar", "bluegrass", "songwriter"],
        "year_range": None,
        "features": {
            "danceability": 0.55,
            "energy": 0.5,
            "loudness": -8.0,
            "speechiness": 0.05,
            "acousticness": 0.6,
            "instrumentalness": 0.05,
            "liveness": 0.18,
            "valence": 0.65,
            "tempo": 108.0,
            "key": 7,
            "mode": 0.8,
            "time_signature": 4,
        }
    },
    {
        "description": "jazz blues soul smooth classic vintage mellow swing",
        "genres": ["jazz", "blues", "soul", "funk", "gospel", "swing"],
        "year_range": (2000, 2020),
        "features": {
            "danceability": 0.55,
            "energy": 0.4,
            "loudness": -11.0,
            "speechiness": 0.05,
            "acousticness": 0.5,
            "instrumentalness": 0.25,
            "liveness": 0.2,
            "valence": 0.5,
            "tempo": 105.0,
            "key": 5,
            "mode": 0.4,
            "time_signature": 4,
        }
    },
    {
        "description": "punk rebellious fast loud raw DIY underground alternative",
        "genres": ["punk", "punk-rock", "alt-rock", "hardcore", "garage", "emo", "rock"],
        "year_range": None,
        "features": {
            "danceability": 0.45,
            "energy": 0.9,
            "loudness": -5.0,
            "speechiness": 0.1,
            "acousticness": 0.04,
            "instrumentalness": 0.05,
            "liveness": 0.25,
            "valence": 0.45,
            "tempo": 165.0,
            "key": 4,
            "mode": 0.5,
            "time_signature": 4,
        }
    },
    {
        "description": "classical orchestral ensemble symphony symphonic philharmonic concerto sonata chamber recital concert auditorium opera epic cinematic film score dramatic",
        "genres": ["classical", "opera", "piano", "show-tunes", "pop-film"],
        "year_range": None,
        "features": {
            "danceability": 0.2,
            "energy": 0.3,
            "loudness": -15.0,
            "speechiness": 0.04,
            "acousticness": 0.8,
            "instrumentalness": 0.85,
            "liveness": 0.12,
            "valence": 0.3,
            "tempo": 95.0,
            "key": 0,
            "mode": 0.4,
            "time_signature": 4,
        }
    },
    {
        "description": "tropical shore summer atmosphere reggae dancehall afrobeat",
        "genres": ["afrobeat", "dancehall", "reggae", "dub", "samba", "salsa", "ska"],
        "year_range": None,
        "features": {
            "danceability": 0.8,
            "energy": 0.65,
            "loudness": -7.0,
            "speechiness": 0.1,
            "acousticness": 0.2,
            "instrumentalness": 0.05,
            "liveness": 0.2,
            "valence": 0.8,
            "tempo": 100.0,
            "key": 7,
            "mode": 0.8,
            "time_signature": 4,
        }
    }
]
